backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        required: false
        field: { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Commissioner", name: "commissioner", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Link", name: "link", widget: "string", required: false }
